### ISSUE TITLE
PCI and MAC address configuration

### ISSUE THREAD

**Issue by ritwix** [SymbioticLab/Kayak#2]
I am trying to enter the right values in the client.toml and server.toml for pci_nic, mac address, and ip address. 
I also find that the setup.sh is not echoing the values for PCI and MAC and instead returns:
+ PCI=
++ ethtool -P ens1f1
++ awk '{ print $3 }'
Cannot read permanent address: No such device
+ MAC=
+ echo 'pci: '
+ echo 'mac: '`

Is there any help you can provide with this? 
Thank you.

**Comment by ritwix** [comment]
I was using the wrong node type in cloudlab configuration.

**Comment by karayanni** [comment]
Hi @ritwix , were you able to run it eventually?
When I run the setup.sh I get a MAC but no PCI, I think the issue might be related to properly installing the MLNX OFED driver, do you remember how you installed it / any insights in general that might be helpful? 
Thanks
